<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Pawsplus.Testing</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\PawsPlus.Domain\PawsPlus.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Bogus" Version="35.6.3" />
    </ItemGroup>

</Project>
