// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using PawsPlus.Infrastructure.Common.Persistence;

#nullable disable

namespace PawsPlus.Infrastructure.Migrations
{
    [DbContext(typeof(PawsPlusDbContext))]
    [Migration("20250423161439_Review_Reviewed")]
    partial class Review_Reviewed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimalPost", b =>
                {
                    b.Property<int>("AnimalsId")
                        .HasColumnType("int");

                    b.Property<string>("PostsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AnimalsId", "PostsId");

                    b.HasIndex("PostsId");

                    b.ToTable("AnimalPost");
                });

            modelBuilder.Entity("BreedPet", b =>
                {
                    b.Property<string>("BreedsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PetsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BreedsId", "PetsId");

                    b.HasIndex("PetsId");

                    b.ToTable("BreedPet");
                });

            modelBuilder.Entity("DateService", b =>
                {
                    b.Property<DateOnly>("AvailableDatesDay")
                        .HasColumnType("date");

                    b.Property<string>("ServicesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AvailableDatesDay", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("DateService");
                });

            modelBuilder.Entity("MeetingPlaceService", b =>
                {
                    b.Property<int>("MeetingPlacesId")
                        .HasColumnType("int");

                    b.Property<string>("ServicesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MeetingPlacesId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("MeetingPlaceService");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cat"
                        });
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Booking", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdditionalDescription")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateOnly>("EndDay")
                        .HasColumnType("date");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetingPlaceId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SitterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("StartDay")
                        .HasColumnType("date");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingPlaceId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SitterId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Breed", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnimalTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.ToTable("Breeds");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AnimalTypeId = 1,
                            Name = "Аффенпинчер"
                        },
                        new
                        {
                            Id = "2",
                            AnimalTypeId = 1,
                            Name = "Афганска хрътка"
                        },
                        new
                        {
                            Id = "3",
                            AnimalTypeId = 1,
                            Name = "Африканско ловно куче"
                        },
                        new
                        {
                            Id = "4",
                            AnimalTypeId = 1,
                            Name = "Еърдейл териер"
                        },
                        new
                        {
                            Id = "5",
                            AnimalTypeId = 1,
                            Name = "Акбаш куче"
                        },
                        new
                        {
                            Id = "6",
                            AnimalTypeId = 1,
                            Name = "Акита"
                        },
                        new
                        {
                            Id = "7",
                            AnimalTypeId = 1,
                            Name = "Алапахски булдог"
                        },
                        new
                        {
                            Id = "8",
                            AnimalTypeId = 1,
                            Name = "Аляски хъски"
                        },
                        new
                        {
                            Id = "9",
                            AnimalTypeId = 1,
                            Name = "Аляски маламут"
                        },
                        new
                        {
                            Id = "10",
                            AnimalTypeId = 1,
                            Name = "Американски булдог"
                        },
                        new
                        {
                            Id = "11",
                            AnimalTypeId = 1,
                            Name = "Американски були"
                        },
                        new
                        {
                            Id = "12",
                            AnimalTypeId = 1,
                            Name = "Американско ескимоско куче"
                        },
                        new
                        {
                            Id = "13",
                            AnimalTypeId = 1,
                            Name = "Американска лисица"
                        },
                        new
                        {
                            Id = "14",
                            AnimalTypeId = 1,
                            Name = "Американски питбул териер"
                        },
                        new
                        {
                            Id = "15",
                            AnimalTypeId = 1,
                            Name = "Американски стафордширски териер"
                        },
                        new
                        {
                            Id = "16",
                            AnimalTypeId = 1,
                            Name = "Американски воден шпаньол"
                        },
                        new
                        {
                            Id = "17",
                            AnimalTypeId = 1,
                            Name = "Анатолийско пастирско куче"
                        },
                        new
                        {
                            Id = "18",
                            AnimalTypeId = 1,
                            Name = "Апенцелер зененхунд"
                        },
                        new
                        {
                            Id = "19",
                            AnimalTypeId = 1,
                            Name = "Австралийско пастирско куче"
                        },
                        new
                        {
                            Id = "20",
                            AnimalTypeId = 1,
                            Name = "Австралийски келпи"
                        },
                        new
                        {
                            Id = "21",
                            AnimalTypeId = 1,
                            Name = "Австралийска овчарка"
                        },
                        new
                        {
                            Id = "22",
                            AnimalTypeId = 1,
                            Name = "Австралийски териер"
                        },
                        new
                        {
                            Id = "23",
                            AnimalTypeId = 1,
                            Name = "Азавах"
                        },
                        new
                        {
                            Id = "24",
                            AnimalTypeId = 1,
                            Name = "Барбе"
                        },
                        new
                        {
                            Id = "25",
                            AnimalTypeId = 1,
                            Name = "Басенджи"
                        },
                        new
                        {
                            Id = "26",
                            AnimalTypeId = 1,
                            Name = "Гасконски басет"
                        },
                        new
                        {
                            Id = "27",
                            AnimalTypeId = 1,
                            Name = "Басет хрътка"
                        },
                        new
                        {
                            Id = "28",
                            AnimalTypeId = 1,
                            Name = "Бийгъл"
                        },
                        new
                        {
                            Id = "29",
                            AnimalTypeId = 1,
                            Name = "Брадато коли"
                        },
                        new
                        {
                            Id = "30",
                            AnimalTypeId = 1,
                            Name = "Босерон"
                        },
                        new
                        {
                            Id = "31",
                            AnimalTypeId = 1,
                            Name = "Бедлингтон териер"
                        },
                        new
                        {
                            Id = "32",
                            AnimalTypeId = 1,
                            Name = "Белгийски малиноа"
                        },
                        new
                        {
                            Id = "33",
                            AnimalTypeId = 1,
                            Name = "Белгийски тервюрен"
                        },
                        new
                        {
                            Id = "34",
                            AnimalTypeId = 1,
                            Name = "Бернско планинско куче"
                        },
                        new
                        {
                            Id = "35",
                            AnimalTypeId = 1,
                            Name = "Бишон фризе"
                        },
                        new
                        {
                            Id = "36",
                            AnimalTypeId = 1,
                            Name = "Черно-тан кунхаунд"
                        },
                        new
                        {
                            Id = "37",
                            AnimalTypeId = 1,
                            Name = "Блъдхаунд"
                        },
                        new
                        {
                            Id = "38",
                            AnimalTypeId = 1,
                            Name = "Блутик кунхаунд"
                        },
                        new
                        {
                            Id = "39",
                            AnimalTypeId = 1,
                            Name = "Бурбул"
                        },
                        new
                        {
                            Id = "40",
                            AnimalTypeId = 1,
                            Name = "Бордър коли"
                        },
                        new
                        {
                            Id = "41",
                            AnimalTypeId = 1,
                            Name = "Бордър териер"
                        },
                        new
                        {
                            Id = "42",
                            AnimalTypeId = 1,
                            Name = "Бостън териер"
                        },
                        new
                        {
                            Id = "43",
                            AnimalTypeId = 1,
                            Name = "Бувие де Фландр"
                        },
                        new
                        {
                            Id = "44",
                            AnimalTypeId = 1,
                            Name = "Боксер"
                        },
                        new
                        {
                            Id = "45",
                            AnimalTypeId = 1,
                            Name = "Бойкин шпаньол"
                        },
                        new
                        {
                            Id = "46",
                            AnimalTypeId = 1,
                            Name = "Брако Италиано"
                        },
                        new
                        {
                            Id = "47",
                            AnimalTypeId = 1,
                            Name = "Бриар"
                        },
                        new
                        {
                            Id = "48",
                            AnimalTypeId = 1,
                            Name = "Бретонски епаньол"
                        },
                        new
                        {
                            Id = "49",
                            AnimalTypeId = 1,
                            Name = "Бул териер"
                        },
                        new
                        {
                            Id = "50",
                            AnimalTypeId = 1,
                            Name = "Бул мастиф"
                        },
                        new
                        {
                            Id = "51",
                            AnimalTypeId = 1,
                            Name = "Керн териер"
                        },
                        new
                        {
                            Id = "52",
                            AnimalTypeId = 1,
                            Name = "Кане корсо"
                        },
                        new
                        {
                            Id = "53",
                            AnimalTypeId = 1,
                            Name = "Уелско корги кардиган"
                        },
                        new
                        {
                            Id = "54",
                            AnimalTypeId = 1,
                            Name = "Куче леопард от Катахула"
                        },
                        new
                        {
                            Id = "55",
                            AnimalTypeId = 1,
                            Name = "Кавказка овчарка"
                        },
                        new
                        {
                            Id = "56",
                            AnimalTypeId = 1,
                            Name = "Кавалер Кинг Чарлз шпаньол"
                        },
                        new
                        {
                            Id = "57",
                            AnimalTypeId = 1,
                            Name = "Чесапийк бей ретрийвър"
                        },
                        new
                        {
                            Id = "58",
                            AnimalTypeId = 1,
                            Name = "Китайско голо качулато куче"
                        },
                        new
                        {
                            Id = "59",
                            AnimalTypeId = 1,
                            Name = "Китайски шарпей"
                        },
                        new
                        {
                            Id = "60",
                            AnimalTypeId = 1,
                            Name = "Чинук"
                        },
                        new
                        {
                            Id = "61",
                            AnimalTypeId = 1,
                            Name = "Чау Чау"
                        },
                        new
                        {
                            Id = "62",
                            AnimalTypeId = 1,
                            Name = "Кламбър шпаньол"
                        },
                        new
                        {
                            Id = "63",
                            AnimalTypeId = 1,
                            Name = "Кокер шпаньол"
                        },
                        new
                        {
                            Id = "64",
                            AnimalTypeId = 1,
                            Name = "Американски кокер шпаньол"
                        },
                        new
                        {
                            Id = "65",
                            AnimalTypeId = 1,
                            Name = "Котон де тулеар"
                        },
                        new
                        {
                            Id = "66",
                            AnimalTypeId = 1,
                            Name = "Далматинец"
                        },
                        new
                        {
                            Id = "67",
                            AnimalTypeId = 1,
                            Name = "Доберман"
                        },
                        new
                        {
                            Id = "68",
                            AnimalTypeId = 1,
                            Name = "Дого Аржентино"
                        },
                        new
                        {
                            Id = "69",
                            AnimalTypeId = 1,
                            Name = "Холандско пастирско куче"
                        },
                        new
                        {
                            Id = "70",
                            AnimalTypeId = 1,
                            Name = "Английски сетер"
                        },
                        new
                        {
                            Id = "71",
                            AnimalTypeId = 1,
                            Name = "Английско пастирско куче"
                        },
                        new
                        {
                            Id = "72",
                            AnimalTypeId = 1,
                            Name = "Английски спрингер шпаньол"
                        },
                        new
                        {
                            Id = "73",
                            AnimalTypeId = 1,
                            Name = "Английски той шпаньол"
                        },
                        new
                        {
                            Id = "74",
                            AnimalTypeId = 1,
                            Name = "Английски териер"
                        },
                        new
                        {
                            Id = "75",
                            AnimalTypeId = 1,
                            Name = "Евразиец"
                        },
                        new
                        {
                            Id = "76",
                            AnimalTypeId = 1,
                            Name = "Полски шпаньол"
                        },
                        new
                        {
                            Id = "77",
                            AnimalTypeId = 1,
                            Name = "Финландско лапландско куче"
                        },
                        new
                        {
                            Id = "78",
                            AnimalTypeId = 1,
                            Name = "Финландски шпиц"
                        },
                        new
                        {
                            Id = "79",
                            AnimalTypeId = 1,
                            Name = "Френски булдог"
                        },
                        new
                        {
                            Id = "80",
                            AnimalTypeId = 1,
                            Name = "Немски пинчер"
                        },
                        new
                        {
                            Id = "81",
                            AnimalTypeId = 1,
                            Name = "Немска овчарка"
                        },
                        new
                        {
                            Id = "82",
                            AnimalTypeId = 1,
                            Name = "Немски късокосмест пойнтер"
                        },
                        new
                        {
                            Id = "83",
                            AnimalTypeId = 1,
                            Name = "Гигантски шнауцер"
                        },
                        new
                        {
                            Id = "84",
                            AnimalTypeId = 1,
                            Name = "Глен ъф Имаал териер"
                        },
                        new
                        {
                            Id = "85",
                            AnimalTypeId = 1,
                            Name = "Голдън ретрийвър"
                        },
                        new
                        {
                            Id = "86",
                            AnimalTypeId = 1,
                            Name = "Гордън сетер"
                        },
                        new
                        {
                            Id = "87",
                            AnimalTypeId = 1,
                            Name = "Немски мастиф"
                        },
                        new
                        {
                            Id = "88",
                            AnimalTypeId = 1,
                            Name = "Пиренейска планинска овчарка"
                        },
                        new
                        {
                            Id = "89",
                            AnimalTypeId = 1,
                            Name = "Грейхаунд"
                        },
                        new
                        {
                            Id = "90",
                            AnimalTypeId = 1,
                            Name = "Грифон брюкселуа"
                        },
                        new
                        {
                            Id = "91",
                            AnimalTypeId = 1,
                            Name = "Харие"
                        },
                        new
                        {
                            Id = "92",
                            AnimalTypeId = 1,
                            Name = "Хаванез"
                        },
                        new
                        {
                            Id = "93",
                            AnimalTypeId = 1,
                            Name = "Ирландски сетер"
                        },
                        new
                        {
                            Id = "94",
                            AnimalTypeId = 1,
                            Name = "Ирландски териер"
                        },
                        new
                        {
                            Id = "95",
                            AnimalTypeId = 1,
                            Name = "Ирландски вълкодав"
                        },
                        new
                        {
                            Id = "96",
                            AnimalTypeId = 1,
                            Name = "Италиански грейхаунд"
                        },
                        new
                        {
                            Id = "97",
                            AnimalTypeId = 1,
                            Name = "Японски чин"
                        },
                        new
                        {
                            Id = "98",
                            AnimalTypeId = 1,
                            Name = "Японски шпиц"
                        },
                        new
                        {
                            Id = "99",
                            AnimalTypeId = 1,
                            Name = "Кеесхонд"
                        },
                        new
                        {
                            Id = "100",
                            AnimalTypeId = 1,
                            Name = "Комондор"
                        },
                        new
                        {
                            Id = "101",
                            AnimalTypeId = 1,
                            Name = "Койкер хондие"
                        },
                        new
                        {
                            Id = "102",
                            AnimalTypeId = 1,
                            Name = "Кувас"
                        },
                        new
                        {
                            Id = "103",
                            AnimalTypeId = 1,
                            Name = "Лабрадор ретрийвър"
                        },
                        new
                        {
                            Id = "104",
                            AnimalTypeId = 1,
                            Name = "Лагото романьоло"
                        },
                        new
                        {
                            Id = "105",
                            AnimalTypeId = 1,
                            Name = "Ланкашир хийлър"
                        },
                        new
                        {
                            Id = "106",
                            AnimalTypeId = 1,
                            Name = "Леонбергер"
                        },
                        new
                        {
                            Id = "107",
                            AnimalTypeId = 1,
                            Name = "Лхаса апсо"
                        },
                        new
                        {
                            Id = "108",
                            AnimalTypeId = 1,
                            Name = "Малтийско болонезе"
                        },
                        new
                        {
                            Id = "109",
                            AnimalTypeId = 1,
                            Name = "Миниатюрна американска овчарка"
                        },
                        new
                        {
                            Id = "110",
                            AnimalTypeId = 1,
                            Name = "Миниатюрен пинчер"
                        },
                        new
                        {
                            Id = "111",
                            AnimalTypeId = 1,
                            Name = "Миниатюрен шнауцер"
                        },
                        new
                        {
                            Id = "112",
                            AnimalTypeId = 1,
                            Name = "Нюфаундленд"
                        },
                        new
                        {
                            Id = "113",
                            AnimalTypeId = 1,
                            Name = "Норфолк териер"
                        },
                        new
                        {
                            Id = "114",
                            AnimalTypeId = 1,
                            Name = "Норич териер"
                        },
                        new
                        {
                            Id = "115",
                            AnimalTypeId = 1,
                            Name = "Нова шотландска патица ретрийвър"
                        },
                        new
                        {
                            Id = "116",
                            AnimalTypeId = 1,
                            Name = "Староанглийско овчарско куче"
                        },
                        new
                        {
                            Id = "117",
                            AnimalTypeId = 1,
                            Name = "Староанглийски булдог"
                        },
                        new
                        {
                            Id = "118",
                            AnimalTypeId = 1,
                            Name = "Папийон"
                        },
                        new
                        {
                            Id = "119",
                            AnimalTypeId = 1,
                            Name = "Пекинез"
                        },
                        new
                        {
                            Id = "120",
                            AnimalTypeId = 1,
                            Name = "Уелско корги пембрук"
                        },
                        new
                        {
                            Id = "121",
                            AnimalTypeId = 1,
                            Name = "Преса канарио"
                        },
                        new
                        {
                            Id = "122",
                            AnimalTypeId = 1,
                            Name = "Фараонско куче"
                        },
                        new
                        {
                            Id = "123",
                            AnimalTypeId = 1,
                            Name = "Плот хаунд"
                        },
                        new
                        {
                            Id = "124",
                            AnimalTypeId = 1,
                            Name = "Померан"
                        },
                        new
                        {
                            Id = "125",
                            AnimalTypeId = 1,
                            Name = "Пудел миниатюрен"
                        },
                        new
                        {
                            Id = "126",
                            AnimalTypeId = 1,
                            Name = "Пудел той"
                        },
                        new
                        {
                            Id = "127",
                            AnimalTypeId = 1,
                            Name = "Мопс"
                        },
                        new
                        {
                            Id = "128",
                            AnimalTypeId = 1,
                            Name = "Пули"
                        },
                        new
                        {
                            Id = "129",
                            AnimalTypeId = 1,
                            Name = "Пуми"
                        },
                        new
                        {
                            Id = "130",
                            AnimalTypeId = 1,
                            Name = "Рат териер"
                        },
                        new
                        {
                            Id = "131",
                            AnimalTypeId = 1,
                            Name = "Редбоун кунхаунд"
                        },
                        new
                        {
                            Id = "132",
                            AnimalTypeId = 1,
                            Name = "Родезийски риджбек"
                        },
                        new
                        {
                            Id = "133",
                            AnimalTypeId = 1,
                            Name = "Ротвайлер"
                        },
                        new
                        {
                            Id = "134",
                            AnimalTypeId = 1,
                            Name = "Руски той териер"
                        },
                        new
                        {
                            Id = "135",
                            AnimalTypeId = 1,
                            Name = "Санбернар"
                        },
                        new
                        {
                            Id = "136",
                            AnimalTypeId = 1,
                            Name = "Салуки"
                        },
                        new
                        {
                            Id = "137",
                            AnimalTypeId = 1,
                            Name = "Самоед"
                        },
                        new
                        {
                            Id = "138",
                            AnimalTypeId = 1,
                            Name = "Шиперке"
                        },
                        new
                        {
                            Id = "139",
                            AnimalTypeId = 1,
                            Name = "Шотландска еленова хрътка"
                        },
                        new
                        {
                            Id = "140",
                            AnimalTypeId = 1,
                            Name = "Шотландски териер"
                        },
                        new
                        {
                            Id = "141",
                            AnimalTypeId = 1,
                            Name = "Шетландско овчарско куче"
                        },
                        new
                        {
                            Id = "142",
                            AnimalTypeId = 1,
                            Name = "Шиба ину"
                        },
                        new
                        {
                            Id = "143",
                            AnimalTypeId = 1,
                            Name = "Ши Тцу"
                        },
                        new
                        {
                            Id = "144",
                            AnimalTypeId = 1,
                            Name = "Шило пастирско куче"
                        },
                        new
                        {
                            Id = "145",
                            AnimalTypeId = 1,
                            Name = "Сибирско хъски"
                        },
                        new
                        {
                            Id = "146",
                            AnimalTypeId = 1,
                            Name = "Визла"
                        },
                        new
                        {
                            Id = "147",
                            AnimalTypeId = 1,
                            Name = "Ваймаранер"
                        },
                        new
                        {
                            Id = "148",
                            AnimalTypeId = 2,
                            Name = "Абисинска"
                        },
                        new
                        {
                            Id = "149",
                            AnimalTypeId = 2,
                            Name = "Австралийска мъгла"
                        },
                        new
                        {
                            Id = "150",
                            AnimalTypeId = 2,
                            Name = "Азиатска"
                        },
                        new
                        {
                            Id = "151",
                            AnimalTypeId = 2,
                            Name = "Американска грубокосместа"
                        },
                        new
                        {
                            Id = "152",
                            AnimalTypeId = 2,
                            Name = "Балийска"
                        },
                        new
                        {
                            Id = "153",
                            AnimalTypeId = 2,
                            Name = "Бенгалска"
                        },
                        new
                        {
                            Id = "154",
                            AnimalTypeId = 2,
                            Name = "Бирманска"
                        },
                        new
                        {
                            Id = "155",
                            AnimalTypeId = 2,
                            Name = "Британска късокосместа"
                        },
                        new
                        {
                            Id = "156",
                            AnimalTypeId = 2,
                            Name = "Бурманска"
                        },
                        new
                        {
                            Id = "157",
                            AnimalTypeId = 2,
                            Name = "Бурмила"
                        },
                        new
                        {
                            Id = "158",
                            AnimalTypeId = 2,
                            Name = "Девон Рекс"
                        },
                        new
                        {
                            Id = "159",
                            AnimalTypeId = 2,
                            Name = "Египетска Мау"
                        },
                        new
                        {
                            Id = "160",
                            AnimalTypeId = 2,
                            Name = "Европейска късокосместа"
                        },
                        new
                        {
                            Id = "161",
                            AnimalTypeId = 2,
                            Name = "Канадски сфинкс"
                        },
                        new
                        {
                            Id = "162",
                            AnimalTypeId = 2,
                            Name = "Корат"
                        },
                        new
                        {
                            Id = "163",
                            AnimalTypeId = 2,
                            Name = "Корниш Рекс"
                        },
                        new
                        {
                            Id = "164",
                            AnimalTypeId = 2,
                            Name = "Мейн Куун"
                        },
                        new
                        {
                            Id = "165",
                            AnimalTypeId = 2,
                            Name = "Норвежка горска"
                        },
                        new
                        {
                            Id = "166",
                            AnimalTypeId = 2,
                            Name = "Ориенталска късокосместа"
                        },
                        new
                        {
                            Id = "167",
                            AnimalTypeId = 2,
                            Name = "Персийска"
                        },
                        new
                        {
                            Id = "168",
                            AnimalTypeId = 2,
                            Name = "Петерболд"
                        },
                        new
                        {
                            Id = "169",
                            AnimalTypeId = 2,
                            Name = "Пикси-боб"
                        },
                        new
                        {
                            Id = "170",
                            AnimalTypeId = 2,
                            Name = "Рагдол"
                        },
                        new
                        {
                            Id = "171",
                            AnimalTypeId = 2,
                            Name = "Руска синя"
                        },
                        new
                        {
                            Id = "172",
                            AnimalTypeId = 2,
                            Name = "Селкирк Рекс"
                        },
                        new
                        {
                            Id = "173",
                            AnimalTypeId = 2,
                            Name = "Серенгети"
                        },
                        new
                        {
                            Id = "174",
                            AnimalTypeId = 2,
                            Name = "Сиамска"
                        },
                        new
                        {
                            Id = "175",
                            AnimalTypeId = 2,
                            Name = "Сибирска"
                        },
                        new
                        {
                            Id = "176",
                            AnimalTypeId = 2,
                            Name = "Сингапурска"
                        },
                        new
                        {
                            Id = "177",
                            AnimalTypeId = 2,
                            Name = "Сомалийска"
                        },
                        new
                        {
                            Id = "178",
                            AnimalTypeId = 2,
                            Name = "Тайска"
                        },
                        new
                        {
                            Id = "179",
                            AnimalTypeId = 2,
                            Name = "Тонкинска"
                        },
                        new
                        {
                            Id = "180",
                            AnimalTypeId = 2,
                            Name = "Турска Ангора"
                        },
                        new
                        {
                            Id = "181",
                            AnimalTypeId = 2,
                            Name = "Турски ван"
                        },
                        new
                        {
                            Id = "182",
                            AnimalTypeId = 2,
                            Name = "Украински Левкой"
                        },
                        new
                        {
                            Id = "183",
                            AnimalTypeId = 2,
                            Name = "Уралски Рекс"
                        },
                        new
                        {
                            Id = "184",
                            AnimalTypeId = 2,
                            Name = "Шартрьо"
                        },
                        new
                        {
                            Id = "185",
                            AnimalTypeId = 2,
                            Name = "Шотландска клепоуха"
                        },
                        new
                        {
                            Id = "186",
                            AnimalTypeId = 2,
                            Name = "Японски бобтейл"
                        });
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Date", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.HasKey("Day");

                    b.ToTable("Dates");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.MeetingPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MeetingPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AtOwners"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AtSitters"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Another"
                        });
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Pet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WeightId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.HasIndex("WeightId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("FirstLogin")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("ReviewedId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("ReviewedId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Weight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SmallToMedium"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MediumToLarge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Large"
                        });
                });

            modelBuilder.Entity("PawsPlus.Infrastructure.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasFilter("[ProfileId] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PostWeight", b =>
                {
                    b.Property<string>("PostsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WeightsId")
                        .HasColumnType("int");

                    b.HasKey("PostsId", "WeightsId");

                    b.HasIndex("WeightsId");

                    b.ToTable("PostWeight");
                });

            modelBuilder.Entity("AnimalPost", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BreedPet", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.Breed", null)
                        .WithMany()
                        .HasForeignKey("BreedsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DateService", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.Date", null)
                        .WithMany()
                        .HasForeignKey("AvailableDatesDay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingPlaceService", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.MeetingPlace", null)
                        .WithMany()
                        .HasForeignKey("MeetingPlacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PawsPlus.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PawsPlus.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawsPlus.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PawsPlus.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Booking", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.MeetingPlace", "MeetingPlace")
                        .WithMany("Bookings")
                        .HasForeignKey("MeetingPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Profile", "Owner")
                        .WithMany("BookingsAsOwner")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Profile", "Sitter")
                        .WithMany("BookingsAsSitter")
                        .HasForeignKey("SitterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PawsPlus.Domain.Models.BookingState", "Status", b1 =>
                        {
                            b1.Property<string>("BookingId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("MeetingPlace");

                    b.Navigation("Owner");

                    b.Navigation("Service");

                    b.Navigation("Sitter");

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Breed", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.Animal", "Animal")
                        .WithMany("Breeds")
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Pet", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Profile", "Profile")
                        .WithOne("Pet")
                        .HasForeignKey("PawsPlus.Domain.Models.Pet", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Weight", "Weight")
                        .WithMany("Pets")
                        .HasForeignKey("WeightId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("PawsPlus.Domain.ValueObjects.Age", "Age", b1 =>
                        {
                            b1.Property<string>("PetId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Months")
                                .HasColumnType("int")
                                .HasColumnName("MonthsOld");

                            b1.Property<int>("Years")
                                .HasColumnType("int")
                                .HasColumnName("YearsOld");

                            b1.HasKey("PetId");

                            b1.ToTable("Pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.OwnsOne("PawsPlus.Domain.ValueObjects.HealthStatus", "HealthStatus", b1 =>
                        {
                            b1.Property<string>("PetId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("HasEatingSchedule")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HasEatingSchedule");

                            b1.Property<string>("HealthProblems")
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)")
                                .HasColumnName("HealthProblems");

                            b1.Property<bool?>("IsCastrated")
                                .HasColumnType("bit")
                                .HasColumnName("IsCastrated");

                            b1.Property<bool?>("IsVaccinated")
                                .HasColumnType("bit")
                                .HasColumnName("IsVaccinated");

                            b1.Property<string>("OtherDietaryNeeds")
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)")
                                .HasColumnName("OtherDietaryNeeds");

                            b1.Property<bool?>("TakesMedications")
                                .HasColumnType("bit")
                                .HasColumnName("TakesMedications");

                            b1.HasKey("PetId");

                            b1.ToTable("Pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.OwnsOne("PawsPlus.Domain.ValueObjects.Personality", "Personality", b1 =>
                        {
                            b1.Property<string>("PetId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("ActivityLevel")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ActivityLevel");

                            b1.Property<string>("FearsDescription")
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)")
                                .HasColumnName("FearsDescription");

                            b1.Property<int?>("HasFears")
                                .HasColumnType("int")
                                .HasColumnName("HasFears");

                            b1.Property<int?>("IsTrained")
                                .HasColumnType("int")
                                .HasColumnName("IsTrained");

                            b1.Property<string>("Temperament")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Temperament");

                            b1.HasKey("PetId");

                            b1.ToTable("Pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.Navigation("Age");

                    b.Navigation("Animal");

                    b.Navigation("HealthStatus");

                    b.Navigation("Personality");

                    b.Navigation("Profile");

                    b.Navigation("Weight");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Post", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.Profile", "Profile")
                        .WithOne("Post")
                        .HasForeignKey("PawsPlus.Domain.Models.Post", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PawsPlus.Domain.Models.PostState", "Status", b1 =>
                        {
                            b1.Property<string>("PostId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("Profile");

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Profile", b =>
                {
                    b.OwnsOne("PawsPlus.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("PlaceId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Point>("Point")
                                .HasColumnType("geometry");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Review", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.Post", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PostId");

                    b.HasOne("PawsPlus.Domain.Models.Profile", "Reviewed")
                        .WithMany("ReceivedReviews")
                        .HasForeignKey("ReviewedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Profile", "Reviewer")
                        .WithMany("GivenReviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reviewed");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Service", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.Post", "Post")
                        .WithMany("Services")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PawsPlus.Infrastructure.Identity.User", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("PawsPlus.Infrastructure.Identity.User", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PostWeight", b =>
                {
                    b.HasOne("PawsPlus.Domain.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawsPlus.Domain.Models.Weight", null)
                        .WithMany()
                        .HasForeignKey("WeightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Animal", b =>
                {
                    b.Navigation("Breeds");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.MeetingPlace", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Post", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Profile", b =>
                {
                    b.Navigation("BookingsAsOwner");

                    b.Navigation("BookingsAsSitter");

                    b.Navigation("GivenReviews");

                    b.Navigation("Pet");

                    b.Navigation("Post");

                    b.Navigation("ReceivedReviews");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Service", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("PawsPlus.Domain.Models.Weight", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
