// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Zoolandia.Infrastructure.Common.Persistence;

#nullable disable

namespace Zoolandia.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ZoolandiaDbContext))]
    partial class ZoolandiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BreedPet", b =>
                {
                    b.Property<string>("BreedsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PetsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BreedsId", "PetsId");

                    b.HasIndex("PetsId");

                    b.ToTable("BreedPet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "020ae868-c87b-429e-bf53-91a164c95bd2",
                            ConcurrencyStamp = "020ae868-c87b-429e-bf53-91a164c95bd2",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = "2b36e6fc-8886-4224-91bb-8b0cfc744627",
                            ConcurrencyStamp = "2b36e6fc-8886-4224-91bb-8b0cfc744627",
                            Name = "Sitter",
                            NormalizedName = "SITTER"
                        },
                        new
                        {
                            Id = "ddd0a343-5d90-46cb-a020-7c2910d436e9",
                            ConcurrencyStamp = "ddd0a343-5d90-46cb-a020-7c2910d436e9",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "33896ccc-d260-415f-bbc1-8379ccf04c0e",
                            RoleId = "ddd0a343-5d90-46cb-a020-7c2910d436e9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Breed", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Breeds");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Аффенпинчер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Афганска хрътка",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Африканско ловно куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Еърдейл териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Акбаш куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "6",
                            Name = "Акита",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "7",
                            Name = "Алапахски булдог",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "8",
                            Name = "Аляски хъски",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "9",
                            Name = "Аляски маламут",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "10",
                            Name = "Американски булдог",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "11",
                            Name = "Американски були",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "12",
                            Name = "Американско ескимоско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "13",
                            Name = "Американска лисица",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "14",
                            Name = "Американски питбул териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "15",
                            Name = "Американски стафордширски териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "16",
                            Name = "Американски воден шпаньол",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "17",
                            Name = "Анатолийско пастирско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "18",
                            Name = "Апенцелер зененхунд",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "19",
                            Name = "Австралийско пастирско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "20",
                            Name = "Австралийски келпи",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "21",
                            Name = "Австралийска овчарка",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "22",
                            Name = "Австралийски териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "23",
                            Name = "Азавах",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "24",
                            Name = "Барбе",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "25",
                            Name = "Басенджи",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "26",
                            Name = "Гасконски басет",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "27",
                            Name = "Басет хрътка",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "28",
                            Name = "Бийгъл",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "29",
                            Name = "Брадато коли",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "30",
                            Name = "Босерон",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "31",
                            Name = "Бедлингтон териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "32",
                            Name = "Белгийски малиноа",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "33",
                            Name = "Белгийски тервюрен",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "34",
                            Name = "Бернско планинско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "35",
                            Name = "Бишон фризе",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "36",
                            Name = "Черно-тан кунхаунд",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "37",
                            Name = "Блъдхаунд",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "38",
                            Name = "Блутик кунхаунд",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "39",
                            Name = "Бурбул",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "40",
                            Name = "Бордър коли",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "41",
                            Name = "Бордър териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "42",
                            Name = "Бостън териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "43",
                            Name = "Бувие де Фландр",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "44",
                            Name = "Боксер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "45",
                            Name = "Бойкин шпаньол",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "46",
                            Name = "Брако Италиано",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "47",
                            Name = "Бриар",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "48",
                            Name = "Бретонски епаньол",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "49",
                            Name = "Бул териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "50",
                            Name = "Бул мастиф",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "51",
                            Name = "Керн териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "52",
                            Name = "Кане корсо",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "53",
                            Name = "Уелско корги кардиган",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "54",
                            Name = "Куче леопард от Катахула",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "55",
                            Name = "Кавказка овчарка",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "56",
                            Name = "Кавалер Кинг Чарлз шпаньол",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "57",
                            Name = "Чесапийк бей ретрийвър",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "58",
                            Name = "Китайско голо качулато куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "59",
                            Name = "Китайски шарпей",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "60",
                            Name = "Чинук",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "61",
                            Name = "Чау Чау",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "62",
                            Name = "Кламбър шпаньол",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "63",
                            Name = "Кокер шпаньол",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "64",
                            Name = "Американски кокер шпаньол",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "65",
                            Name = "Котон де тулеар",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "66",
                            Name = "Далматинец",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "67",
                            Name = "Доберман",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "68",
                            Name = "Дого Аржентино",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "69",
                            Name = "Холандско пастирско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "70",
                            Name = "Английски сетер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "71",
                            Name = "Английско пастирско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "72",
                            Name = "Английски спрингер шпаньол",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "73",
                            Name = "Английски той шпаньол",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "74",
                            Name = "Английски териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "75",
                            Name = "Евразиец",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "76",
                            Name = "Полски шпаньол",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "77",
                            Name = "Финландско лапландско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "78",
                            Name = "Финландски шпиц",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "79",
                            Name = "Френски булдог",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "80",
                            Name = "Немски пинчер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "81",
                            Name = "Немска овчарка",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "82",
                            Name = "Немски късокосмест пойнтер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "83",
                            Name = "Гигантски шнауцер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "84",
                            Name = "Глен ъф Имаал териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "85",
                            Name = "Голдън ретрийвър",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "86",
                            Name = "Гордън сетер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "87",
                            Name = "Немски мастиф",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "88",
                            Name = "Пиренейска планинска овчарка",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "89",
                            Name = "Грейхаунд",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "90",
                            Name = "Грифон брюкселуа",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "91",
                            Name = "Харие",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "92",
                            Name = "Хаванез",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "93",
                            Name = "Ирландски сетер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "94",
                            Name = "Ирландски териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "95",
                            Name = "Ирландски вълкодав",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "96",
                            Name = "Италиански грейхаунд",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "97",
                            Name = "Японски чин",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "98",
                            Name = "Японски шпиц",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "99",
                            Name = "Кеесхонд",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "100",
                            Name = "Комондор",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "101",
                            Name = "Койкер хондие",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "102",
                            Name = "Кувас",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "103",
                            Name = "Лабрадор ретрийвър",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "104",
                            Name = "Лагото романьоло",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "105",
                            Name = "Ланкашир хийлър",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "106",
                            Name = "Леонбергер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "107",
                            Name = "Лхаса апсо",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "108",
                            Name = "Малтийско болонезе",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "109",
                            Name = "Миниатюрна американска овчарка",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "110",
                            Name = "Миниатюрен пинчер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "111",
                            Name = "Миниатюрен шнауцер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "112",
                            Name = "Нюфаундленд",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "113",
                            Name = "Норфолк териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "114",
                            Name = "Норич териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "115",
                            Name = "Нова шотландска патица ретрийвър",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "116",
                            Name = "Староанглийско овчарско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "117",
                            Name = "Староанглийски булдог",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "118",
                            Name = "Папийон",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "119",
                            Name = "Пекинез",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "120",
                            Name = "Уелско корги пембрук",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "121",
                            Name = "Преса канарио",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "122",
                            Name = "Фараонско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "123",
                            Name = "Плот хаунд",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "124",
                            Name = "Померан",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "125",
                            Name = "Пудел миниатюрен",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "126",
                            Name = "Пудел той",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "127",
                            Name = "Мопс",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "128",
                            Name = "Пули",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "129",
                            Name = "Пуми",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "130",
                            Name = "Рат териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "131",
                            Name = "Редбоун кунхаунд",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "132",
                            Name = "Родезийски риджбек",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "133",
                            Name = "Ротвайлер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "134",
                            Name = "Руски той териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "135",
                            Name = "Санбернар",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "136",
                            Name = "Салуки",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "137",
                            Name = "Самоед",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "138",
                            Name = "Шиперке",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "139",
                            Name = "Шотландска еленова хрътка",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "140",
                            Name = "Шотландски териер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "141",
                            Name = "Шетландско овчарско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "142",
                            Name = "Шиба ину",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "143",
                            Name = "Ши Тцу",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "144",
                            Name = "Шило пастирско куче",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "145",
                            Name = "Сибирско хъски",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "146",
                            Name = "Визла",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "147",
                            Name = "Ваймаранер",
                            PetType = "Dog"
                        },
                        new
                        {
                            Id = "148",
                            Name = "Абисинска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "149",
                            Name = "Австралийска мъгла",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "150",
                            Name = "Азиатска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "151",
                            Name = "Американска грубокосместа",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "152",
                            Name = "Балийска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "153",
                            Name = "Бенгалска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "154",
                            Name = "Бирманска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "155",
                            Name = "Британска късокосместа",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "156",
                            Name = "Бурманска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "157",
                            Name = "Бурмила",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "158",
                            Name = "Девон Рекс",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "159",
                            Name = "Египетска Мау",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "160",
                            Name = "Европейска късокосместа",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "161",
                            Name = "Канадски сфинкс",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "162",
                            Name = "Корат",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "163",
                            Name = "Корниш Рекс",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "164",
                            Name = "Мейн Куун",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "165",
                            Name = "Норвежка горска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "166",
                            Name = "Ориенталска късокосместа",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "167",
                            Name = "Персийска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "168",
                            Name = "Петерболд",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "169",
                            Name = "Пикси-боб",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "170",
                            Name = "Рагдол",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "171",
                            Name = "Руска синя",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "172",
                            Name = "Селкирк Рекс",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "173",
                            Name = "Серенгети",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "174",
                            Name = "Сиамска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "175",
                            Name = "Сибирска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "176",
                            Name = "Сингапурска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "177",
                            Name = "Сомалийска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "178",
                            Name = "Тайска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "179",
                            Name = "Тонкинска",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "180",
                            Name = "Турска Ангора",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "181",
                            Name = "Турски ван",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "182",
                            Name = "Украински Левкой",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "183",
                            Name = "Уралски Рекс",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "184",
                            Name = "Шартрьо",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "185",
                            Name = "Шотландска клепоуха",
                            PetType = "Cat"
                        },
                        new
                        {
                            Id = "186",
                            Name = "Японски бобтейл",
                            PetType = "Cat"
                        });
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Pet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetType")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PetTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Weights")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FirstLogin")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvailableDates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Zoolandia.Infrastructure.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasFilter("[ProfileId] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "33896ccc-d260-415f-bbc1-8379ccf04c0e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ba416b33-d51a-403a-9496-3f9b8587bfba",
                            Email = "hristopanev20@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HRISTOPANEV20@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEG/vPoGvgalVLrMeU5FRRSvVUo/F0G074AUgbKWGbmNORr7CBeF0igt2h418Nn34FA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf6c4666-82b2-4e46-85d1-c79a0ae4e58d",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("BreedPet", b =>
                {
                    b.HasOne("Zoolandia.Domain.Models.Breed", null)
                        .WithMany()
                        .HasForeignKey("BreedsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoolandia.Domain.Models.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Zoolandia.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Zoolandia.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoolandia.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Zoolandia.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Pet", b =>
                {
                    b.HasOne("Zoolandia.Domain.Models.Profile", "Profile")
                        .WithOne("Pet")
                        .HasForeignKey("Zoolandia.Domain.Models.Pet", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoolandia.Domain.ValueObjects.Age", "Age", b1 =>
                        {
                            b1.Property<string>("PetId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Months")
                                .HasColumnType("int")
                                .HasColumnName("MonthsOld");

                            b1.Property<int>("Years")
                                .HasColumnType("int")
                                .HasColumnName("YearsOld");

                            b1.HasKey("PetId");

                            b1.ToTable("Pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.OwnsOne("Zoolandia.Domain.ValueObjects.HealthStatus", "HealthStatus", b1 =>
                        {
                            b1.Property<string>("PetId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("HasEatingSchedule")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HasEatingSchedule");

                            b1.Property<string>("HealthProblems")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HealthProblems");

                            b1.Property<bool?>("IsCastrated")
                                .IsRequired()
                                .HasColumnType("bit")
                                .HasColumnName("IsCastrated");

                            b1.Property<bool?>("IsVaccinated")
                                .IsRequired()
                                .HasColumnType("bit")
                                .HasColumnName("IsVaccinated");

                            b1.Property<string>("OtherDietaryNeeds")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("OtherDietaryNeeds");

                            b1.Property<bool?>("TakesMedications")
                                .IsRequired()
                                .HasColumnType("bit")
                                .HasColumnName("TakesMedications");

                            b1.HasKey("PetId");

                            b1.ToTable("Pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.OwnsOne("Zoolandia.Domain.ValueObjects.Personality", "Personality", b1 =>
                        {
                            b1.Property<string>("PetId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("ActivityLevel")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ActivityLevel");

                            b1.Property<string>("FearsDescription")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FearsDescription");

                            b1.Property<int>("HasFears")
                                .HasColumnType("int")
                                .HasColumnName("HasFears");

                            b1.Property<int>("IsTrained")
                                .HasColumnType("int")
                                .HasColumnName("IsTrained");

                            b1.Property<string>("Temperament")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Temperament");

                            b1.HasKey("PetId");

                            b1.ToTable("Pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.Navigation("Age");

                    b.Navigation("HealthStatus");

                    b.Navigation("Personality");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Post", b =>
                {
                    b.HasOne("Zoolandia.Domain.Models.Profile", "Profile")
                        .WithOne("Post")
                        .HasForeignKey("Zoolandia.Domain.Models.Post", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoolandia.Domain.Models.StateType", "Status", b1 =>
                        {
                            b1.Property<string>("PostId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("Profile");

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Profile", b =>
                {
                    b.OwnsOne("Zoolandia.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("PlaceId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Point>("Point")
                                .HasColumnType("geometry");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Service", b =>
                {
                    b.HasOne("Zoolandia.Domain.Models.Post", "Post")
                        .WithMany("Services")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Zoolandia.Infrastructure.Identity.User", b =>
                {
                    b.HasOne("Zoolandia.Domain.Models.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("Zoolandia.Infrastructure.Identity.User", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Post", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Zoolandia.Domain.Models.Profile", b =>
                {
                    b.Navigation("Pet");

                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
